/** Declaration file generated by dts-gen */

export function add(
  subdomains: string,
  tokens: string,
  cookies: string,
  options: any
): any

export function download(
  subdomains: string,
  tokens: string,
  cookies: string,
  options: any
): any

export function favorites(
  subdomains: string,
  tokens: string,
  cookies: string,
  options: any
): any

export function sync(
  subdomains: string,
  tokens: string,
  cookies: string,
  options: any
): any

export function upload(
  subdomains: string,
  tokens: string,
  cookies: string,
  options: any
): any

export function userStats(
  subdomains: string,
  tokens: string,
  cookies: string,
  options: any
): any
